### ISSUE TITLE
File 15-clipped-segment.tex is empty

### ISSUE THREAD

**Issue by rafaelpap** [PacktPublishing/LaTeX-graphics-with-TikZ#2]
I belive that file 15-clipped-segment.tex should contains something like:

\documentclass[tikz,border=2pt]{standalone}
\begin{document}
\begin{tikzpicture}[even odd rule]
\clip (-3,0) rectangle (3,2);
\clip (-1,0) circle (1.2) (-1,0) circle (2);
\fill[red!70] (1,0) circle (1.2) (1,0) circle (2);
\end{tikzpicture}
\end{document}

**Comment by StefanKottwitz** [comment]
Thank you, I added the missing code!
